Feature/tools
Rover656/EnderIO-Rewrite-Old pull request #25
Opened 2021-10-24 18:37 UTC by agnor99

# Description

Added Yeta Wrench:
- Changed the rotation to only allow for valid blockstates
Added the Coordination Selector and Location Printout

# Todo 

- [x] Lang Datagen
- [x] ItemStack Capability
- [x] PR to Art-Repo to fix texture rename and missing gui texture

# Checklist:

- [x] My code follows the style guidelines of this project (.editorconfig, most IDEs will use this for you)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2021-10-24 18:39 UTC, justliliandev commented
I've also renamed renderers to renderer because package names are in singular form

2021-11-02 13:02 UTC, Rover656 requested changes

2021-11-02 13:02 UTC, Rover656 commented on enderio-base/src/main/java/com/enderio/base/client/screen/CoordinateMenuScreen.java
> +    protected void renderLabels(PoseStack pPoseStack, int pMouseX, int pMouseY) {
Can we maybe move some common code ino an EIOScreen class or something? I feel like this override and a load others are going to be pretty common...

2021-11-02 13:02 UTC, Rover656 commented on enderio-base/src/main/java/com/enderio/base/common/menu/CoordinateMenu.java
> +        /**
Formatting error :)

2021-11-02 13:02 UTC, Rover656 commented on enderio-base/src/main/java/com/enderio/base/common/menu/CoordinateMenu.java
> +
Blank space :)

2021-11-02 13:02 UTC, Rover656 commented on enderio-base/src/main/java/com/enderio/base/common/network/EIOPackets.java
> +        new ResourceLocation(EnderIO.DOMAIN, "network"), //TODO: Enderio.rl
TODO now invalid, you can change this

2021-11-02 14:25 UTC, CrazyPants commented on enderio-base/src/main/java/com/enderio/base/common/capability/location/ICoordinateSelection.java
> +    void set(boolean isSet);
setSet, or maybe setIsSet

2021-11-02 14:41 UTC, CrazyPants commented on enderio-base/src/main/java/com/enderio/base/common/item/tool/CoordinateSelectorItem.java
> +    public static void openMenu(ServerPlayer player, BlockPos pos, ResourceLocation dimension) {
this looks like it should be a private non-static method

2021-11-02 14:44 UTC, CrazyPants commented on enderio-base/src/main/java/com/enderio/base/common/menu/CoordinateMenu.java
> +
Some unused imports

2021-11-02 15:31 UTC, CrazyPants commented on enderio-base/src/main/java/com/enderio/base/client/screen/CoordinateMenuScreen.java
> +import com.enderio.base.common.capability.location.CoordinateSelection;
unused import

2021-11-02 15:52 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/client/screen/CoordinateMenuScreen.java
> +    protected void renderLabels(PoseStack pPoseStack, int pMouseX, int pMouseY) {
I created a blank EIOScreen in EnderCore with EditBoxHelpers for all screens

2021-11-02 16:34 UTC, Rover656 commented on enderio-base/src/main/java/com/enderio/base/client/screen/CoordinateMenuScreen.java
> +    protected void renderLabels(PoseStack pPoseStack, int pMouseX, int pMouseY) {
Looking good :)

2021-11-02 16:34 UTC, Rover656 approved these changes

2021-11-02 16:34 UTC, Rover656 commented
All good for merge if we're all happy :)

2021-11-02 16:35 UTC, Rover656 commented
Uh actually, GH Actions failed; mind having a look?

2021-11-04 04:54 UTC, CrazyPants approved these changes

2021-11-04 14:33 UTC, Rover656 commented
Nice work; thanks :)

2021-11-04 14:33 UTC, merged