Implemented tree felling in Dark Steel Axe
Rover656/EnderIO-Rewrite-Old pull request #39
Opened 2021-11-22 11:57 UTC by CrazyPants

# Description

Added the Direct upgrade
Added the dual energy/durability bar
Added recipes for tools and upgrades

# Checklist:

- [ ] My code follows the style guidelines of this project (.editorconfig, most IDEs will use this for you)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2021-11-23 14:37 UTC, agnor99 requested changes

2021-11-23 14:37 UTC, justliliandev commented on enderio-base/src/main/java/com/enderio/base/client/renderer/DarkSteelDurabilityRenderer.java
> +            ENERGY_BAR_RGB >> 16 & 255, ENERGY_BAR_RGB >> 8 & 255, ENERGY_BAR_RGB & 255);
Maybe use FastColor.ARGB32 for better readability

2021-11-23 14:37 UTC, justliliandev commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +            if(pEntityLiving.isCrouching() && pState.is(BlockTags.LOGS) && EnergyUtil.getEnergyStored(pStack) > 0) {
spaces between if and (

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +    private void fellTree(Level level, BlockPos pos, Set<BlockPos> checkedPos, Set<BlockPos> toChop, int maxBlocks, Block targetBock) {
could u add javadoc for each parameter?

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +        res.add(pos.south().west());
suggestion:
I think this is more readable
```suggestion
        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                if (x != 0 || z != 0) {
                  res.add(pos.offset(x, 0, z);
                }
            }
        }
```

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +        res.add(pos.south().west());
suggestion:
I think this is more readable
```suggestion
        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                if (x != 0 || z != 0) {
                  res.add(pos.offset(x, 0, z));
                }
            }
        }
```

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +        res.add(pos.south().west());
or:
```suggestion
        for (int x = -1; x <= 1; x++) {
            for (int z = -1; z <= 1; z++) {
                res.add(pos.offset(x, 0, z));
            }
        }
        res.remove(pos);
```

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +        //NB: going through all the steps rather than using level.destroyBlock so that stats are updated, hunger is used etc
BlockEvent.BreakEvent is not getting fired

2021-11-23 14:37 UTC, agnor99 commented on enderio-base/src/main/java/com/enderio/base/common/lang/EIOLang.java
> +    public static final TranslatableComponent ENERGY_AMOUNT = REGISTRATE.addLang("info", EnderIO.loc("energy.amount"), "%s μI");
replace μ with \\u00B5

2021-11-24 05:57 UTC, CrazyPants commented on enderio-base/src/main/java/com/enderio/base/common/item/darksteel/DarkSteelAxeItem.java
> +            if(pEntityLiving.isCrouching() && pState.is(BlockTags.LOGS) && EnergyUtil.getEnergyStored(pStack) > 0) {
Booo! How do you see these? I tried so hard to make sure all the spaces where good! lol

2021-11-24 11:28 UTC, merged